name: reactive_button
description: "Reactive Button"
version: 0.0.6
repository: "https://github.com/mahdinazmi/Reactive-Button"

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.0
  dartz: ^0.10.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
